name: Build Desktop Packages

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS (Universal DMG)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build DMG (universal)
        run: npm run build:mac
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG
          path: dist/*.dmg

  build-windows:
    name: Windows (MSI x64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install WiX Toolset
        shell: pwsh
        run: |
          choco install wixtoolset -y
      - name: Install dependencies
        run: npm ci
      - name: Build MSI
        run: npm run build:win
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: Windows-MSI
          path: dist/*.msi

  build-linux:
    name: Linux (AppImage x64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build AppImage
        run: npm run build:linux
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Linux-AppImage
          path: dist/*.AppImage
